version = 1
SPDX-PackageName = "grendel"
SPDX-PackageDownloadLocation = "https://github.com/ubccr/grendel"

[[annotations]]
path = [
    "go.mod",
    "go.sum",
    ".gitmodules",
    ".actrc",
    ".air.toml",
    "docs/pyproject.toml",
    "NOTICE",
    "configs/grendel.toml.sample",
    "docs/requirements.txt",
    "internal/firmware/Makefile",
    "internal/firmware/boot.ipxe",
    "scripts/**",
    "**.yaml",
    "**.yml",
    "**.tmpl",
    "**.md",
    "**.sql",
    "**.gitignore",
    "**.go",
    "**.tsx",
    "**.ts",
    "**.html",
    "**.css",
    "**.js",
    "**.json",
    "**.lock",
]
SPDX-FileCopyrightText = "(C) 2019 Grendel Authors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "docs/pages/images/*",
    "internal/frontend/src/assets/*",
    "**.ico",
]
SPDX-FileCopyrightText = "(C) 2019 Grendel Authors"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

[[annotations]]
path = "internal/frontend/src/components/ui/*"
SPDX-FileCopyrightText = "(C) 2023 shadcn"
SPDX-License-Identifier = "MIT"
