site_name: Grendel
docs_dir: 'pages'
site_description: 'Bare metal provision system for high performance Linux clusters'
site_url: 'https://github.com/ubccr/grendel'
copyright: 'Copyright &copy; 2019 Center for Computational Research, University at Buffalo'
repo_name: 'ubccr/grendel'
repo_url: 'https://github.com/ubccr/grendel'
edit_uri: ''

theme:
  name: 'material'
  palette:
    primary: 'black'
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

nav:
    - What is Grendel?: index.md
    - Installation: install.md
    - Quick Start: quickstart.md
    - Background: background.md
    - Production Deployments: production.md
    - Publications: publications.md
    - Advanced:
        - Dynamic DHCP Router: advanced/router.md
        - HTTPS and Code Signing: advanced/https.md
        - Kickstarting Live Images: advanced/kslive.md
